first commit
fix CIs

fix env name + rm rtd

make pre install config simple

clean and rm old refs

remove check_estimator

add makefile

add stuff in Manifest

use jit

update gigignore

rm OS files

ignore circleci in manifest

fix typo

fix typo

fix typo

fix test + group lasso

update travis badge

update readme

fix badge

add gl example

add example

update test + normalization

fix doc

fix the doc

fix makefile

update doc

update gigitgnore

rm cache

update manifest

update gitignore

update theme

update readme

rm requirements

fix circleci

fix path in circleci

add dependency

rm circlci

update doc

fix badges

clean up docs

update docs

docs good

fix predict and score funcs + doc

add dirty example

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -12,38 +12,34 @@ matrix:
     - env: PYTHON_VERSION="3.5" NUMPY_VERSION="1.13.1" SCIPY_VERSION="0.19.1"
            SKLEARN_VERSION="0.19.1"
     - env: PYTHON_VERSION="3.6" NUMPY_VERSION="1.13.1" SCIPY_VERSION="0.19.1"
-           SKLEARN_VERSION="0.20.3"
+           SKLEARN_VERSION="0.19.1"
     - env: PYTHON_VERSION="3.7" NUMPY_VERSION="*" SCIPY_VERSION="*"
            SKLEARN_VERSION="*"
-    - env: PYTHON_VERSION="3.7" NUMPY_VERSION="*" SCIPY_VERSION="*"
-           SKLEARN_VERSION="nightly"
 
-install:
+before_install:
   # install miniconda
   - deactivate
   - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
   - MINICONDA_PATH=/home/travis/miniconda
   - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
   - export PATH=$MINICONDA_PATH/bin:$PATH
-  - conda update --yes conda
+  - conda update --yes --quiet conda
   # create the testing environment
-  - conda create -n testenv --yes python=$PYTHON_VERSION pip
-  - source activate testenv
-  - |
-      if [ $SKLEARN_VERSION = "nightly" ]; then
-          conda install --yes numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION cython nose pytest pytest-cov
-          # install nightly wheels
-          pip install --pre -f https://sklearn-nightly.scdn8.secure.raxcdn.com scikit-learn
-      else
-          conda install --yes numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION scikit-learn==$SKLEARN_VERSION cython nose pytest pytest-cov
-      fi
+  - conda env create --file environment.yml python=${PYTHON_VERSION}
+  - source activate mutar-env
+  - conda install --yes --quiet pytest pytest-cov coverage
+  - pip install flake8 check-manifest
   - pip install codecov
-  - pip install .
+
+install:
+  - python setup.py build_ext --inplace
+  - pip install -e .
 
 script:
-  - mkdir for_test
-  - cd for_test
-  - pytest -v --cov=mutar --pyargs mutar
-
+  - export NUMBA_DISABLE_JIT=1
+  - pytest -lv --cov-report term-missing mutar --cov=mutar --cov-config .coveragerc
+  - make
+  - flake8 --count mutar
 after_success:
-  - codecov
+  - cp .coverage $TRAVIS_BUILD_DIR
+  - codecov --root $TRAVIS_BUILD_DIR || echo "codecov upload failed"
